" .vimrc
syntax on
colo peachpuff

set autoindent
set bs=2
set cindent
set directory=/tmp/
set expandtab
set incsearch
set lisp
set list
set listchars=tab:..,trail:.
set nocompatible
set noerrorbells
set nohlsearch
set novisualbell
set nowrap
set paste
set path=**
set ruler
set shiftwidth=2
set shortmess+=I
set showmatch
set smarttab
set tabstop=2
set ts=2
set wildmode=longest,list
set foldmethod=indent
set foldlevelstart=99
set complete=.,b,u,]
set spell spelllang=en_us
set nospell
set ignorecase
set rnu
set smartcase
